### ISSUE TITLE
William John Van Patten's Contributions

### ISSUE THREAD

**Issue by wjvanpatten** [connormeredithcu/Meredith_CSCI2270_FinalProject#3]
Due to a lack of permissions and my inability to make a branch I've provided my contributions here (TA's: More details on the assignment submission on moodle).

In main the changes were

...
int main()
{
//...
        if(choice=="2") //William John Van Patten's new function
        {
            MultipleInput(&mimic);
        }
...

In utilities.h the additional function was

...
//Gives the suer an option to input many sentences at once
void MultipleInput(ResponseHandler \* g);
...

In utilities.cpp the function details are

...
void MultipleInput(ResponseHandler \* g)
{
    string sInputs2;
    cout << "How many sentences do you want to input?" << endl
         << "> "                                           ;
    cin >> sInputs2;
    cin.ignore();
    int numInteractions = StringToInt(sInputs2);

```
for (int i = 0; i < numInteractions; i++)
{
    TakeSentence(g);
}
```

}
...

**Comment by wjvanpatten** [comment]
Also, feel free to close this issue so your repo looks nice and tidy.

**Comment by connormeredithcu** [comment]
Looks good. I'll add your code and update the repo.
